name: "[npm] Build, Attest, and Push to npmjs.com"

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the npm package
        run: npm run build

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}" > ~/.npmrc
    
      - name: Publish the npm package to npmjs.com
        run: npm publish --provenance --access public

    